import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

export async function up({ payload, req }: MigrateUpArgs): Promise<void> {
  await payload.db.drizzle.run(sql`CREATE INDEX \`pages_blocks_hero_high_impact_high_impact_image_idx\` ON \`pages_blocks_hero\` (\`high_impact_image_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`pages_blocks_history_image_idx\` ON \`pages_blocks_history\` (\`image_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`pages_blocks_donate_image_idx\` ON \`pages_blocks_donate\` (\`image_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`pages_blocks_links_block_link_cards_image_idx\` ON \`pages_blocks_links_block_link_cards\` (\`image_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`pages_blocks_form_block_form_idx\` ON \`pages_blocks_form_block\` (\`form_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`pages_meta_metadata_meta_metadata_image_idx\` ON \`pages\` (\`meta_metadata_image_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`pages_rels_pages_id_idx\` ON \`pages_rels\` (\`pages_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`pages_rels_media_id_idx\` ON \`pages_rels\` (\`media_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`pages_rels_events_id_idx\` ON \`pages_rels\` (\`events_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`_pages_v_blocks_hero_high_impact_high_impact_image_idx\` ON \`_pages_v_blocks_hero\` (\`high_impact_image_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`_pages_v_blocks_history_image_idx\` ON \`_pages_v_blocks_history\` (\`image_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`_pages_v_blocks_donate_image_idx\` ON \`_pages_v_blocks_donate\` (\`image_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`_pages_v_blocks_links_block_link_cards_image_idx\` ON \`_pages_v_blocks_links_block_link_cards\` (\`image_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`_pages_v_blocks_form_block_form_idx\` ON \`_pages_v_blocks_form_block\` (\`form_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`_pages_v_parent_idx\` ON \`_pages_v\` (\`parent_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`_pages_v_version_meta_metadata_version_meta_metadata_image_idx\` ON \`_pages_v\` (\`version_meta_metadata_image_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`_pages_v_rels_pages_id_idx\` ON \`_pages_v_rels\` (\`pages_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`_pages_v_rels_media_id_idx\` ON \`_pages_v_rels\` (\`media_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`_pages_v_rels_events_id_idx\` ON \`_pages_v_rels\` (\`events_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`forms_event_idx\` ON \`forms\` (\`event_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`form_submissions_form_idx\` ON \`form_submissions\` (\`form_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`redirects_rels_pages_id_idx\` ON \`redirects_rels\` (\`pages_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`payload_locked_documents_rels_pages_id_idx\` ON \`payload_locked_documents_rels\` (\`pages_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`payload_locked_documents_rels_events_id_idx\` ON \`payload_locked_documents_rels\` (\`events_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`payload_locked_documents_rels_media_id_idx\` ON \`payload_locked_documents_rels\` (\`media_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`payload_locked_documents_rels_users_id_idx\` ON \`payload_locked_documents_rels\` (\`users_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`payload_locked_documents_rels_forms_id_idx\` ON \`payload_locked_documents_rels\` (\`forms_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`payload_locked_documents_rels_form_submissions_id_idx\` ON \`payload_locked_documents_rels\` (\`form_submissions_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`payload_locked_documents_rels_redirects_id_idx\` ON \`payload_locked_documents_rels\` (\`redirects_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`payload_preferences_rels_users_id_idx\` ON \`payload_preferences_rels\` (\`users_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`header_rels_pages_id_idx\` ON \`header_rels\` (\`pages_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`header_rels_media_id_idx\` ON \`header_rels\` (\`media_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`footer_rels_pages_id_idx\` ON \`footer_rels\` (\`pages_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`footer_rels_media_id_idx\` ON \`footer_rels\` (\`media_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`company_info_rels_pages_id_idx\` ON \`company_info_rels\` (\`pages_id\`);`)
  await payload.db.drizzle.run(sql`CREATE INDEX \`company_info_rels_media_id_idx\` ON \`company_info_rels\` (\`media_id\`);`)
}

export async function down({ payload, req }: MigrateDownArgs): Promise<void> {
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`pages_blocks_hero_high_impact_high_impact_image_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`pages_blocks_history_image_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`pages_blocks_donate_image_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`pages_blocks_links_block_link_cards_image_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`pages_blocks_form_block_form_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`pages_meta_metadata_meta_metadata_image_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`pages_rels_pages_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`pages_rels_media_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`pages_rels_events_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`_pages_v_blocks_hero_high_impact_high_impact_image_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`_pages_v_blocks_history_image_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`_pages_v_blocks_donate_image_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`_pages_v_blocks_links_block_link_cards_image_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`_pages_v_blocks_form_block_form_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`_pages_v_parent_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`_pages_v_version_meta_metadata_version_meta_metadata_image_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`_pages_v_rels_pages_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`_pages_v_rels_media_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`_pages_v_rels_events_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`forms_event_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`form_submissions_form_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`redirects_rels_pages_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`payload_locked_documents_rels_pages_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`payload_locked_documents_rels_events_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`payload_locked_documents_rels_media_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`payload_locked_documents_rels_users_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`payload_locked_documents_rels_forms_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`payload_locked_documents_rels_form_submissions_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`payload_locked_documents_rels_redirects_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`payload_preferences_rels_users_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`header_rels_pages_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`header_rels_media_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`footer_rels_pages_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`footer_rels_media_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`company_info_rels_pages_id_idx\`;`)
  await payload.db.drizzle.run(sql`DROP INDEX IF EXISTS \`company_info_rels_media_id_idx\`;`)
}
